a1 = input('digite algo: ')
print('qual a tipo é?: ', type(a1))
print('é alfanumérico?', a1.isalnum())
print('é alfabético?', a1.isalpha())
print('é minúsculo?', a1.islower())
print('é decimal?', a1.isdecimal())
print('é numérico?', a1.isnumeric())
print('é um espaço? ', a1.isspace())
print('é maiúsculo?', a1.isupper())
print('é com 1° letra maiúscula?', a1.istitle())
